sudo: false
language: "node_js"
node_js: 
  - "8"
  - "10"
install: 
  - npm install
script: npm run test
after_success:
  - cat ./tests/coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - cat ./tests/coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./tests/coverage